AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    Route53HostedZone:
        Type: "AWS::Route53::HostedZone"
        Properties:
            Name: !Ref Route53RecordSet

    CertificateManagerCertificate:
        Type: "AWS::CertificateManager::Certificate"
        Properties:
            DomainName: "mystaticwebsiteproject.com"
            SubjectAlternativeNames: 
              - "mystaticwebsiteproject.com"
              - "*.mystaticwebsiteproject.com"
            DomainValidationOptions: 
              - 
                DomainName: "mystaticwebsiteproject.com"
                ValidationDomain: "mystaticwebsiteproject.com"
              - 
                DomainName: "*.mystaticwebsiteproject.com"
                ValidationDomain: "*.mystaticwebsiteproject.com"
            CertificateTransparencyLoggingPreference: "ENABLED"

    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: "s3bucket.mystaticwebsiteproject.com"
            BucketEncryption: 
                ServerSideEncryptionConfiguration: 
                  - 
                    ServerSideEncryptionByDefault: 
                        SSEAlgorithm: "AES256"
                    BucketKeyEnabled: true
            VersioningConfiguration: 
                Status: "Enabled"
            OwnershipControls: 
                Rules: 
                  - 
                    ObjectOwnership: "BucketOwnerEnforced"
            PublicAccessBlockConfiguration: 
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    CloudFrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            DistributionConfig: 
                Origins: 
                  - 
                    ConnectionAttempts: 3
                    ConnectionTimeout: 10
                    DomainName: !Sub "${S3Bucket}.s3.${AWS::Region}.amazonaws.com"
                    Id: !Sub "${S3Bucket}.s3.${AWS::Region}.amazonaws.com"
                    OriginPath: ""
                    S3OriginConfig: 
                        OriginAccessIdentity: "origin-access-identity/cloudfront/EYMF5AY3A2H1G"
                DefaultCacheBehavior: 
                    AllowedMethods: 
                      - "HEAD"
                      - "GET"
                    CachedMethods: 
                      - "HEAD"
                      - "GET"
                    Compress: true
                    CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
                    SmoothStreaming: false
                    TargetOriginId: !Sub "${S3Bucket}.s3.${AWS::Region}.amazonaws.com"
                    ViewerProtocolPolicy: "allow-all"
                Comment: ""
                PriceClass: "PriceClass_All"
                Enabled: true
                ViewerCertificate: 
                    CloudFrontDefaultCertificate: true
                    MinimumProtocolVersion: "TLSv1"
                    SslSupportMethod: "vip"
                Restrictions: 
                    GeoRestriction: 
                        RestrictionType: "none"
                HttpVersion: "http2"
                DefaultRootObject: ""
                IPV6Enabled: true

    Route53RecordSet:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: !Ref Route53RecordSet2
            Type: "A"
            AliasTarget: 
                HostedZoneId: "Z2FDTNDATAQYW2"
                DNSName: "d1l0n7a7sa3z83.cloudfront.net."
                EvaluateTargetHealth: false
            HostedZoneId: "Z077380023VZ9FHZW9EN7"

    Route53RecordSet2:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: !Ref Route53RecordSet3
            Type: "NS"
            TTL: 172800
            ResourceRecords: 
              - "ns-55.awsdns-06.com."
              - "ns-939.awsdns-53.net."
              - "ns-1444.awsdns-52.org."
              - "ns-1885.awsdns-43.co.uk."
            HostedZoneId: "Z077380023VZ9FHZW9EN7"

    Route53RecordSet3:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: "mystaticwebsiteproject.com."
            Type: "SOA"
            TTL: 900
            ResourceRecords: 
              - "ns-55.awsdns-06.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"
            HostedZoneId: "Z077380023VZ9FHZW9EN7"

    Route53RecordSet4:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: !Sub "_1227722484017e62bdbb386c97e6e360.${Route53RecordSet}"
            Type: "CNAME"
            TTL: 300
            ResourceRecords: 
              - "_d9b79f3c72c3662312e4a89ea1ebeca7.tctnwhlsjt.acm-validations.aws."
            HostedZoneId: !Ref Route53HostedZone

    Route53RecordSet5:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: !Sub "${S3Bucket}."
            Type: "CNAME"
            TTL: 300
            ResourceRecords: 
              - "mystaticwebsiteproject.com"
            HostedZoneId: !Ref Route53HostedZone

